# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Openv < Formula
  desc "A tool to automatically load secrets from env files using 1password cli u"
  homepage "https://github.com/andrea11/openv"
  url "https://github.com/andrea11/openv/archive/refs/tags/v0.1.4.tar.gz"
  version "0.1.4"
  sha256 "cec53f21f6bbec418f35af85dc3fb79bc52fbed201fbf75c07a441ad524d4f70"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/andrea11/openv/releases/download/v0.1.4/openv-0.1.4-darwin-arm64.tar.gz"
      sha256 "52908692d1189afde722b9077bd9607be5d462929adbeb9b43b8257d6a2fe3b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrea11/openv/releases/download/v0.1.4/openv-0.1.4-linux-amd64.tar.gz"
      sha256 "7b29a3e069dd4ac32db5aba941c18cb6b96c4e812520db1df37935403cef1b0b"
    end

    on_arm do
      url "https://github.com/andrea11/openv/releases/download/v0.1.4/openv-0.1.4-linux-arm64.tar.gz"
      sha256 "a9a1e634ea7525da4664d02b979bc9e4baf50797098fd6e11185e5f34d731a91"
    end
  end

  def install
    bin.install "openv"
  end

  test do
    assert_match "--help", shell_output("openv --help")
  end
end
