# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Openv < Formula
  desc "A tool to automatically load secrets from .env files using 1password cli u"
  homepage "https://github.com/andrea11/openv"
  url "https://github.com/andrea11/openv/archive/refs/tags/v0.3.0.tar.gz"
  version "0.3.0"
  sha256 "19e0866e65c98379194a835d542ed3fb22bf3c92c9e30c5afb7252baa54bcde8"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/andrea11/openv/releases/download/v0.3.0/openv-0.3.0-darwin-arm64.tar.gz"
      sha256 "af23879f2591fcb913d7522915154328fb2c49d8e349239a9ec97ae2aaaa2d32"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrea11/openv/releases/download/v0.3.0/openv-0.3.0-linux-amd64.tar.gz"
      sha256 "b9c89782ae277299bd9ae37963412cf21e5469d7be3d91e822d833836953bd1e"
    end

    on_arm do
      url "https://github.com/andrea11/openv/releases/download/v0.3.0/openv-0.3.0-linux-arm64.tar.gz"
      sha256 "d3c5b1101d46ff41320c2ec3801ed200c56dc48cdeaa129e7c551e368e08d5a3"
    end
  end

  def install
    bin.install "openv"
  end

  test do
    assert_match "--help", shell_output("openv --help")
  end
end
