# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Openv < Formula
  desc "A tool to automatically load secrets from env files"
  homepage "https://github.com/andrea11/openv"
  url "https://github.com/andrea11/openv/archive/refs/tags/v0.1.0.tar.gz"
  version "0.1.0"
  sha256 "91caecfbaf4c55cbc68b9b71fbae6b68da95b04f7988eb16721b2b69451c4e6a"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/andrea11/openv/releases/download/v0.1.0/openv-0.1.0-darwin-arm64.tar.gz"
      sha256 "3da0b88f8a2a4cc0fe6398424e8dc8ed854d5cd7ccc4faa6298bcb968a23f00d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrea11/openv/releases/download/v0.1.0/openv-0.1.0-linux-amd64.tar.gz"
      sha256 "59d7e2919c2c18d203dee5b1fe06fab93fbdb6e8e83cad4cf30b98eefd5e4597"
    end

    on_arm do
      url "https://github.com/andrea11/openv/releases/download/v0.1.0/openv-0.1.0-linux-arm64.tar.gz"
      sha256 "677ca738a85972af6ead3ac7a4c834d41807a269cf8f39049f4254a16f45df79"
    end
  end

  def install
    bin.install "openv"
  end

  test do
    assert_match "--help", shell_output("openv --help")
  end
end
